import { useEffect, useCallback } from 'react';
import type { NextPage } from 'next'
import Head from 'next/head'
import { Title } from '@kilo-lab/web-design.title';
import { Header } from '@kilo-lab/web-design.header';
import { IoEarth } from 'react-icons/io5';
import styled from 'styled-components';
import { Page, TitleGraphic, CardLink, Footer } from '../components';
import { useTheme } from '../theme';
import { useLogin } from '../hooks';

const Link = styled.p`
  font-size: 90px;
  margin: 0;
  cursor: pointer;
  &:hover {
    text-decoration: underline;
  }
`;

const Main = styled.div`
  min-height: 100vh;
  padding: 4rem 0;
  flex: 1;
  display: flex;
  flex-direction: column;
  justify-content: center;
  align-items: center;
`;

const Grid = styled.div`
  display: flex;
  align-items: center;
  justify-content: space-evenly;
  flex-wrap: wrap;
  max-width: 800px;
  width: 100%;
  margin: 20px 0px;
`;

const Description = styled.p`
  margin: 4rem 0;
  line-height: 1.5;
  font-size: 1.5rem;
`;

const Code = styled.code`
  background: #fafafa;
  border-radius: 5px;
  padding: 0.75rem;
  font-size: 1.1rem;
  font-family: Menlo, Monaco, Lucida Console, Liberation Mono, DejaVu Sans Mono,
    Bitstream Vera Sans Mono, Courier New, monospace;
`;

const Home: NextPage = () => {

  const [theme] = useTheme();

  const [login, { loading }] = useLogin();

  useEffect(() => {
    login();
  }, []);

  return (
    <Page>
      <Head>
        <title>KiloLab Next Template</title>
        <meta name="description" content="Generated by KiloLab NextJS Templates" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header
        zIndex={100}
        LeftElement={
          <IoEarth
            style={{ marginRight: '10px' }}
            color="white"
            size={20}
          />
        }
        color="white"
        backgroundColor={theme.colors.primary}
        title="KiloLab NextJS Template"
        position="fixed"
        top="0"
        left={0}
        right={0}
        width="100%"
      />
      <Main>
        <TitleGraphic
          marginTop="50px"
          src="/earth_spin.svg"
          imageProps={{
            src: '/earth_spin.svg',
            width: 700,
            height: 700
          }}
          title={
            <Title marginTop="100px" marginLeft="-150px" color="black" fontSize={90}>
              Welcome to<br />
              <Link style={{ color: theme.colors.primary }}>
                KiloLab&apos;s NextJS<br />
                Template
              </Link>
            </Title>
          }
        />

        <Description>
          Get started by editing{' '}
          <Code>pages/index.tsx</Code>
        </Description>

        <Grid>
          <CardLink
            width="250px"
            height="200px"
            padding="10px 20px"
            background={theme.colors.primary}
            href="https://www.kilolab.co.za"
            target="_blank"
            transition="all 0.1s linear"
            _hover={{
              opacity: 1,
              boxShadow: '0px 0px 10px grey',
              color: theme.colors.secondary
            }}
            boxShadow="0px 0px 5px grey"
          >
            <h2>Custom Softare &rarr;</h2>
            <p>Looking for Custom Software? Visit our home page and tell us what you&apos;re looking for!</p>
          </CardLink>
          <CardLink
            width="250px"
            height="200px"
            padding="10px 20px"
            background={theme.colors.primary}
            href="https://styled-system.com/"
            target="_blank"
            transition="all 0.1s linear"
            _hover={{
              opacity: 1,
              boxShadow: '0px 0px 10px grey',
              color: theme.colors.secondary
            }}
            boxShadow="0px 0px 5px grey"
          >
            <h2>Styled System &rarr;</h2>
            <p>We build our components using styled system! We know...we like it too. Check out their home page here.</p>
          </CardLink>
        </Grid>
        <Grid>
          <CardLink
            width="250px"
            height="200px"
            padding="10px 20px"
            background={theme.colors.primary}
            href="https://bit.cloud/kilo-lab/web-design"
            target="_blank"
            transition="all 0.1s linear"
            _hover={{
              opacity: 1,
              boxShadow: '0px 0px 10px grey',
              color: theme.colors.secondary
            }}
            boxShadow="0px 0px 5px grey"
          >
            <h2>Components &rarr;</h2>
            <p>Want to make your own Components? Visit our component registry and publish using Bit!</p>
          </CardLink>
        </Grid>
      </Main>

      <Footer
        background={theme.colors.primary}
        logo={<TitleGraphic
          width="300px"
          src="/earth_footer.svg"
          imageProps={{
            src: '/earth_footer.svg',
            width: 200,
            height: 200,
          }}
          title={
            <Title color="white" fontSize="30px" marginLeft="-50px">
              KiloLab
              <br />
              Pty Ltd
            </Title>
          }
        />}
        _content={{display: 'flex', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'stretch', width: '400px', height: '200px'}}
      >
        <div style={{color: 'white'}}>
          <Title color="white">
            Location
          </Title>
          <p style={{fontSize:"14px"}}>
            51 Mount Du Roche Crescent<br />
            Somerset Ridge<br />
            Somerset West<br />
            Cape Town<br />
            7130<br />
          </p>
        </div>
        <div style={{color: 'white'}}>
          <Title color="white">
            Contact Us
          </Title>
          <p>
            info@kilolab.co.za
            <br />
            +27 84 254 8270
          </p>
        </div>
      </Footer>
    </Page>
  )
}

export default Home
